# Generated by Django 5.1.4 on 2025-01-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apptracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("company", models.CharField(max_length=120)),
                ("applied", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="Todo",
        ),
    ]
